---
k8smaster: 
  hosts: &K8S_MASTER
    pdl-kube-01:

k8sworkers:
  hosts: &K8S_WORKERS
    pdl-kube-0[2:4]:

k8s:
  hosts:
    <<: [ *K8S_MASTER, *K8S_WORKERS ]
  vars:
    deploy_target: pi

jenkins:
  hosts:
    pdl-tooling-01:
