---
# Required roles
- name: geerlingguy.nfs
  version: 2.0.0
- name: geerlingguy.swap
  version: 1.0.2
- name: geerlingguy.containerd
  version: 1.1.1
- name: geerlingguy.kubernetes
  version: 6.0.0
