# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geerlingguy/ubuntu2004"
  config.ssh.insert_key = false
  config.vm.provider "virtualbox"
  
  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 2
    v.linked_clone = true
    v.customize ['modifyvm', :id, '--audio', 'none']
  end

  # Define four VMs with static private IP addresses.
  boxes = [
    { :name => "vtl-kube-01", :ip => "192.168.77.2" },
    { :name => "vtl-kube-02", :ip => "192.168.77.3" },
    { :name => "vtl-kube-03", :ip => "192.168.77.4" },
    { :name => "vtl-kube-04", :ip => "192.168.77.5" }
  ]

  # Configure each of the VMs.
  boxes.each_with_index do |opts, index|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name] + ".kube.test"
      config.vm.network :private_network, ip: opts[:ip]

      # Provision all the VMs using Ansible after last VM is up.
      if index == boxes.size - 1
        config.vm.provision "ansible" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.playbook = "../../main.yml"
          ansible.inventory_path = "hosts.yml"
          ansible.limit = "all"
          #ansible.raw_arguments = ["-vvv"]
        end
      end
    end
  end

end
